pawtyplanner/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path

from pawtyplannerbackend import views


urlpatterns = [
    # url(r'', views.home),
    path('pawtyplannerbackend/', include('pawtyplannerbackend.urls')),
    url(r'^api/public/', views.public),
    url(r'^api/private/', views.private),
    url(r'admin/', admin.site.urls)
]

pawtyplannerbackend/urls.py
from django.conf.urls import url
from pawtyplannerbackend import views

app_name = 'pawtyplannerbackend'

urlpatterns = [
    url(r'home/', views.home, name='home'),
    url(r'buy/', views.buy, name='buy'),
    url(r'gallery/', views.gallery, name='gallery'),
    url(r'contact/', views.contact, name='contact'),
    url(r'checkout/', views.checkout, name='checkout')
]

pawtyplannerbackend/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=50, unique=True)
    price = models.FloatField()
    picture = models.ImageField()

    def __str__(self):
        return self.name


class Design(models.Model):
    name = models.CharField(max_length=50, unique=True)
    picture = models.ImageField()

    def __str__(self):
        return self.name


class Order(models.Model):
    order_number = models.IntegerField(unique=True)
    price = models.FloatField()

    def __str__(self):
        return str(self.order_number)


class ProductOrder(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    design = models.ForeignKey('Design', on_delete=models.CASCADE, blank=True)
    quantity = models.IntegerField()
    order = models.ForeignKey('Order', on_delete=models.CASCADE)

    def __str__(self):
        return self.product.name


class Customer(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

catalog/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view
from django.http import HttpResponse


def public(request):
    return HttpResponse("You don't need to be authenticated to see this")


@api_view(['GET'])
def private(request):
    return HttpResponse("You should not see this message if not authenticated!")

pawtyplannerbackend/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view
from django.http import HttpResponse


def home(request):
    return render(request, 'pawtyplannerbackend/home.html')


def buy(request):
    return render(request, 'pawtyplannerbackend/buy.html')


def gallery(request):
    return render(request, 'pawtyplannerbackend/gallery.html')


def contact(request):
    return render(request, 'pawtyplannerbackend/contact.html')


def checkout(request):
    return render(request, 'pawtyplannerbackend/checkout.html')


def public(request):
    return HttpResponse("You don't need to be authenticated to see this")


@api_view(['GET'])
def private(request):
    return HttpResponse("You should not see this message if not authenticated!")

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>The Pawty Planner</title>
    </head>
    <body>
        <div>
            <img src="{% static 'pawty.png' %}" alt="The Pawty Planner logo - dog wearing party hat"
                        width="150" height="150"/>
            <a href="{% url 'pawtyplannerbackend:home' %}">Home</a>
            <a href="{% url 'pawtyplannerbackend:buy' %}">Buy</a>
            <a href="{% url 'pawtyplannerbackend:gallery' %}">Gallery</a>
            <a href="{% url 'pawtyplannerbackend:contact' %}">Contact Us</a>
            <a href="{% url 'pawtyplannerbackend:checkout' %}">Checkout</a>
        </div>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

templates/pawtyplannerbackend/buy.html
{% extends 'base.html' %}

{% block body_block %}
    <h1>Buy page</h1>
{% endblock %}

templates/pawtyplannerbackend/checkout.html
{% extends 'base.html' %}

{% block body_block %}
    <h1>Checkout page</h1>
{% endblock %}

templates/pawtyplannerbackend/contact.html
{% extends 'base.html' %}

{% block body_block %}
    <h1>Contact page</h1>
{% endblock %}

templates/pawtyplannerbackend/gallery.html
{% extends 'base.html' %}

{% block body_block %}
    <h1>Gallery page</h1>
{% endblock %}

templates/pawtyplannerbackend/home.html
{% extends 'base.html' %}

{% block body_block %}
    <h1>Home page</h1>
{% endblock %}